# Generated by Django 6.0.3 on 2026-04-09 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.DateTimeField(auto_now_add=True)),
                ('pgn_data', models.TextField()),
                ('white_accuracy', models.FloatField(default=0.0)),
                ('black_accuracy', models.FloatField(default=0.0)),
                ('white_rating_est', models.IntegerField(default=0)),
                ('black_rating_est', models.IntegerField(default=0)),
                ('brilliant_count', models.IntegerField(default=0)),
                ('great_count', models.IntegerField(default=0)),
                ('best_count', models.IntegerField(default=0)),
                ('excelllent_count', models.IntegerField(default=0)),
                ('good_count', models.IntegerField(default=0)),
                ('inaccuracy_count', models.IntegerField(default=0)),
                ('miss_count', models.IntegerField(default=0)),
                ('mistake_count', models.IntegerField(default=0)),
                ('blunder_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MoveAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_number', models.IntegerField()),
                ('notation', models.CharField(max_length=10)),
                ('fen', models.TextField()),
                ('evaluation', models.FloatField()),
                ('classification', models.CharField(max_length=20)),
                ('explanation', models.TextField(blank=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='analysis.savedanalysis')),
            ],
        ),
    ]
