# Generated by Django 6.0.3 on 2026-04-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedanalysis',
            name='book_count',
            field=models.IntegerField(default=0),
        ),
    ]
