# Generated by Django 6.0.3 on 2026-04-12 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_savedanalysis_book_count'),
        ('user', '0003_game_unique_user_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedanalysis',
            name='eco_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='savedanalysis',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='user.game'),
        ),
        migrations.AddField(
            model_name='savedanalysis',
            name='opening',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
