# Generated by Django 6.0.3 on 2026-04-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_savedanalysis_eco_code_savedanalysis_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedanalysis',
            name='black_end_acc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedanalysis',
            name='black_mid_acc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedanalysis',
            name='black_opening_acc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedanalysis',
            name='white_end_acc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedanalysis',
            name='white_mid_acc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedanalysis',
            name='white_opening_acc',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
