# Generated by Django 6.0.3 on 2026-04-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_savedanalysis_black_end_acc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedanalysis',
            name='full_payload',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
