# Generated by Django 6.0.3 on 2026-04-12 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_savedanalysis_full_payload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedanalysis',
            old_name='excelllent_count',
            new_name='excellent_count',
        ),
    ]
