# Generated by Django 6.0.4 on 2026-04-16 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_savedanalysis_result_reason'),
        ('user', '0003_game_unique_user_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedanalysis',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='user.game'),
        ),
    ]
