# Generated by Django 6.0.4 on 2026-04-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0008_alter_savedanalysis_game"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedanalysis",
            name="analysis_engine_version",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="savedanalysis",
            name="opening_confidence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="savedanalysis",
            name="opening_source",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="savedanalysis",
            name="review_algo_version",
            field=models.IntegerField(default=0),
        ),
    ]
