# Generated by Django 6.0.3 on 2026-04-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='black_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='white_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
