# Generated by Django 6.0.3 on 2026-04-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_game_black_rating_game_white_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.UniqueConstraint(fields=('user', 'game_id'), name='unique_user_game_id'),
        ),
    ]
