# Generated by Django 6.0.3 on 2026-04-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_game_fetched_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chess_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
